# Generated by Django 5.1.2 on 2024-11-07 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='brand',
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='shares_outstanding',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividends',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_splits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='stock.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
