# Generated by Django 5.1.2 on 2024-11-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_brand_industry_remove_stock_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividends',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='shares_outstanding',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock_splits',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AddField(
            model_name='stock',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('dividends', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_splits', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shares_outstanding', models.BigIntegerField(default=0)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='stock.stock')),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
